// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lin
double lin(NumericVector x, NumericVector y, double pt, int n_x);
RcppExport SEXP linBilin_lin(SEXP xSEXP, SEXP ySEXP, SEXP ptSEXP, SEXP n_xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    __result = Rcpp::wrap(lin(x, y, pt, n_x));
    return __result;
END_RCPP
}
// bilin
double bilin(const arma::vec& pt, const arma::vec& x, const arma::vec& y, const arma::vec& f, int n_x, int n_y);
RcppExport SEXP linBilin_bilin(SEXP ptSEXP, SEXP xSEXP, SEXP ySEXP, SEXP fSEXP, SEXP n_xSEXP, SEXP n_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type f(fSEXP);
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_y(n_ySEXP);
    __result = Rcpp::wrap(bilin(pt, x, y, f, n_x, n_y));
    return __result;
END_RCPP
}
// trilin
double trilin(const arma::vec& pt, const arma::vec& x, const arma::vec& y, const arma::vec& z, const arma::mat& m_f, int n_x, int n_y, int n_z);
RcppExport SEXP linBilin_trilin(SEXP ptSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP m_fSEXP, SEXP n_xSEXP, SEXP n_ySEXP, SEXP n_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type m_f(m_fSEXP);
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_y(n_ySEXP);
    Rcpp::traits::input_parameter< int >::type n_z(n_zSEXP);
    __result = Rcpp::wrap(trilin(pt, x, y, z, m_f, n_x, n_y, n_z));
    return __result;
END_RCPP
}
// trilin_z
double trilin_z(const arma::vec& pt, const arma::vec& x, const arma::vec& y, const arma::mat& z, const arma::mat& m_f, int n_x, int n_y, int n_z);
RcppExport SEXP linBilin_trilin_z(SEXP ptSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP m_fSEXP, SEXP n_xSEXP, SEXP n_ySEXP, SEXP n_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type m_f(m_fSEXP);
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_y(n_ySEXP);
    Rcpp::traits::input_parameter< int >::type n_z(n_zSEXP);
    __result = Rcpp::wrap(trilin_z(pt, x, y, z, m_f, n_x, n_y, n_z));
    return __result;
END_RCPP
}
// trilin_inv
double trilin_inv(const arma::vec& pt, const arma::vec& x, const arma::vec& y, const arma::vec& z, const arma::mat& m_f, int n_x, int n_y, int n_z);
RcppExport SEXP linBilin_trilin_inv(SEXP ptSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP m_fSEXP, SEXP n_xSEXP, SEXP n_ySEXP, SEXP n_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type m_f(m_fSEXP);
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_y(n_ySEXP);
    Rcpp::traits::input_parameter< int >::type n_z(n_zSEXP);
    __result = Rcpp::wrap(trilin_inv(pt, x, y, z, m_f, n_x, n_y, n_z));
    return __result;
END_RCPP
}
