# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lin <- function(x, y, pt, n_x) {
    .Call('linBilin_lin', PACKAGE = 'linBilin', x, y, pt, n_x)
}

bilin <- function(pt, x, y, f, n_x, n_y) {
    .Call('linBilin_bilin', PACKAGE = 'linBilin', pt, x, y, f, n_x, n_y)
}

trilin <- function(pt, x, y, z, m_f, n_x, n_y, n_z) {
    .Call('linBilin_trilin', PACKAGE = 'linBilin', pt, x, y, z, m_f, n_x, n_y, n_z)
}

trilin_z <- function(pt, x, y, z, m_f, n_x, n_y, n_z) {
    .Call('linBilin_trilin_z', PACKAGE = 'linBilin', pt, x, y, z, m_f, n_x, n_y, n_z)
}

trilin_inv <- function(pt, x, y, z, m_f, n_x, n_y, n_z) {
    .Call('linBilin_trilin_inv', PACKAGE = 'linBilin', pt, x, y, z, m_f, n_x, n_y, n_z)
}

